---
# AdoptOpenJDK variables file
Jenkins_User_SSHKey: /root/keys/id_rsa.pub
Zeus_User_SSHKey: /root/keys/zeus.key
Jenkins_Username: jenkins
Nagios_Plugins: Enabled
Slack_Notification: Enabled
Superuser_Account: Enabled
