########################################
# AdoptOpenJDK - Ansible Playbook for: #
# ----- RHEL 7 on x86 and s390 ------  #
########################################

################
# Please Note: #
################
# RHEL systems must be registered with the Red Hat Subscription Management service before this Playbook can be used.

- hosts: all
  remote_user: root
  become: yes
  tasks:
  - block:

    ######################
    # Load variable file #
    ######################
    - name: Load AdoptOpenJDKs variable file
      include_vars: adoptopenjdk_variables.yml
      
    ###############################
    # Update and Install Packages #
    ###############################
    - name: yum upgrade all packages
      yum: name='*' state=latest update_cache=yes
  
    - name: Install Build tools
      yum: name={{item}} state=installed 
      with_items:
        - alsa-lib-devel
        - bind-utils
        - cpanminus
        - cpio
        - cups-devel
        - freetype-devel
        - gcc
        - gcc-c++
        - git
        - glibc
        - glibc-common
        - java-1.8.0-openjdk-devel
        - libXext-devel
        - libXrender-devel
        - libXrender-devel
        - libXt-devel
        - libXt-devel
        - libXtst-devel
        - libXtst-devel
        - make
        - mesa-libGL-devel
        - ntp
        - openssl-devel
        - perl-CPAN
        - wget
        - zip

    - name: Install Test tools
      yum: name={{item}} state=installed
      with_items:
        - ant
        - perl
        - xorg-x11-xauth

    - name: Install xorg-x11-server-Xorg if host is x86_64
      yum: name=xorg-x11-server-Xorg state=installed
      when: (ansible_architecture == "x86_64")

    - name: Install xorg-x11-server-common if host is s390x
      yum: name=xorg-x11-server-common state=installed
      when: (ansible_architecture == "s390x")
      
    - name: Download and Install JQ
      get_url:
        url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
        dest: /usr/bin/jq
        mode: 0755
        
    ###############
    # ant-contrib #
    ###############
    - name: Download ant-contrib
      get_url:
        url: https://sourceforge.net/projects/ant-contrib/files/ant-contrib/ant-contrib-1.0b2/ant-contrib-1.0b2-bin.tar.gz
        dest: /tmp/
        mode: 0440
        timeout: 25

    - name: Extract ant-contrib
      unarchive:
        src: /tmp/ant-contrib-1.0b2-bin.tar.gz 
        dest: /tmp/
        copy: False

    - name: Move ant-contrib.jar to lib folder
      command: mv /tmp/ant-contrib/lib/ant-contrib.jar /usr/share/ant/lib/

    - name: Clean ant-contrib tmp files
      file:
        state: absent
        path: "/tmp/ant-contrib/"

    - file:
        state: absent
        path: "/tmp/ant-contrib-1.0b2-bin.tar.gz"

    ################
    # Jenkins user #
    ################
    - name: Create jenkins user
      action: user name={{ Jenkins_Username }} state=present
      ignore_errors: yes

    - name: Create Jenkins user home folder
      file:
        path: /home/{{ Jenkins_Username }}
        state: directory
        owner: "{{ Jenkins_Username }}"
        group: "{{ Jenkins_Username }}"
        mode: 0700
      when: (ansible_architecture == "s390x")
      
    - name: Set authorized key for jenkins user
      authorized_key:
        user: "{{ Jenkins_Username }}"
        state: present
        key: "{{ lookup('file', '{{ Jenkins_User_SSHKey }}') }}"

    #######################
    # Additional Packages #
    #######################
    - name: Download ccache.tar.gz
      get_url:
        url: https://www.samba.org/ftp/ccache/ccache-3.1.9.tar.gz
        dest: /home/{{ Jenkins_Username }}/ccache.tar.gz
        mode: 0440
      
    - name: Extract ccache
      unarchive:
        src: /home/{{ Jenkins_Username }}/ccache.tar.gz
        dest: /home/{{ Jenkins_Username }}
        copy: False

    - name: Running ./configure & make for CCACHE
      shell: cd /home/{{ Jenkins_Username }}/ccache-3.1.9 && ./configure && make && sudo make install
      become: yes

    - name: Install JSON
      shell: |
        cpanm --with-recommends JSON

    - name: Install Text::CSV
      shell: |
        cpanm --with-recommends Text::CSV      

    ##################
    # Nagios plugins #
    ##################
    - name: Include Nagios Playbook
      include_tasks: nagios/nagios_rhel_7.yml
      when: Nagios_Plugins == "Enabled"

    #####################
    # superuser account #
    #####################
    - name: Setup zeus user
      shell: useradd zeus --shell /bin/bash -m 
      ignore_errors: yes
      when: Superuser_Account == "Enabled"

    - name: Create SSH Key folder for zeus
      file: 
        path: /home/zeus/.ssh
        owner: zeus
        group: zeus
        mode: 0700
        state: directory
      when: Superuser_Account == "Enabled"

    - name: Add key
      authorized_key:
        user: zeus
        state: present
        key: "{{ lookup('file', '{{ Zeus_User_SSHKey }}') }}"
      when: Superuser_Account == "Enabled"

    - name: Grant zeus sudo powers
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^zeus'
        line: 'zeus ALL=(ALL) NOPASSWD: ALL'
      when: Superuser_Account == "Enabled"

    #############
    # swap file #
    ############# 
    - stat: path=/swapfile
      register: swap_test

    - name: Create swap file
      command: fallocate -l 2G /swapfile
      when: swap_test.stat.exists == false 

    - name: Set swap file permissions
      file: path=/swapfile
            owner=root
            group=root
            mode=0600
      when: swap_test.stat.exists == false

    - name: Create swap area device
      command: mkswap /swapfile
      when: swap_test.stat.exists == false
      
    - name: Mount swap file
      command: swapon /swapfile
      when: swap_test.stat.exists == false

    - name: Add swap to fstab
      mount: src=/swapfile
        name=none
        fstype=swap
        opts=sw
        passno=0
        dump=0
        state=present
      when: swap_test.stat.exists == false
      
    ####################
    # Auto OS patching #
    ####################    
    - name: Add cron job to check for updates
      cron: name="Check for Updates every Sunday at 5am"
            weekday="6"
            minute="0"
            hour="5"
            user=root
            job="/usr/bin/yum -y update"
            state=present

    ###############
    # X11 Support #
    ###############
    - name: Create X11 Wrapper config file
      copy:
        content: |
          allowed_users=anybody
          needs_root_rights=yes
        dest: /etc/X11/Xwrapper.config
        group: root
        owner: root
        mode: 0644

    - name: Start X11
      become: yes
      become_user: "{{ Jenkins_Username }}"
      shell: startx -- :1 &
      ignore_errors: yes
      no_log: True
              
    ###################
    # NTP Time Server #
    ###################
    - name: Set timedatectl set-ntp no
      shell: timedatectl set-ntp no

    - name: Configure NTP server pools
      shell: cat /etc/ntp.conf | grep "1.pool.ntp.org" && echo "" || echo -e "pool 1.pool.ntp.org\npool 2.pool.ntp.org\npool 3.pool.ntp.org" >> /etc/ntp.conf
      
    - name: Start NTP
      service:
        name: ntpd
        state: restarted

    ############
    # Clean up #
    ############
    - name: Remove yum dependencies that are no longer required
      command: yum -y autoremove
      args:
         warn: no

    ################
    # Pass or Fail #
    ################
    - name: Send Slack notification, successful
      include_tasks: slack_notification/successful_slack.yml
      when: Slack_Notification == "Enabled"

    rescue:
    - name: Send Slack notification, failure
      include_tasks: slack_notification/failure_slack.yml
      when: Slack_Notification == "Enabled"
